apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/lcarva/manylinux?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "calunga"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: lucarval-test
    appstudio.openshift.io/component: lucarval-manylinux
    pipelines.appstudio.openshift.io/type: build
  name: lucarval-manylinux-on-push
  namespace: calunga-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/calunga-tenant/lucarval-manylinux:{{revision}}
    - name: path-context
      value: docker
  taskRunTemplate:
    serviceAccountName: build-pipeline-lucarval-manylinux
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
  pipelineRef:
    name: build
status: {}
